### 레디스 데이터 등록
POST http://localhost:8080/redis
Content-Type: application/json

{
  "value": "설명"
}

### KEY LIST 조회
GET http://localhost:8080/redis/keys


### 단일 데이터 조회
GET http://localhost:8080/redis/78c19812-b301-4bb6-93b3-720249b7d1df


### 단일 데이터 삭제
DELETE http://localhost:8080/redis/78c19812-b301-4bb6-93b3-720249b7d1df
